/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMinutesRouteImport } from './routes/_authenticated/minutes'
import { Route as AuthenticatedImportantRouteImport } from './routes/_authenticated/important'
import { Route as AuthenticatedDiscardedRouteImport } from './routes/_authenticated/discarded'
import { Route as AuthenticatedControlCenterRouteImport } from './routes/_authenticated/control-center'
import { Route as AuthenticatedAdministratorRouteImport } from './routes/_authenticated/administrator'
import { Route as AuthenticatedVisibilityIndexRouteImport } from './routes/_authenticated/visibility.index'
import { Route as AuthenticatedServiceabilityIndexRouteImport } from './routes/_authenticated/serviceability.index'
import { Route as AuthenticatedPriorityIndexRouteImport } from './routes/_authenticated/priority/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedIntelIndexRouteImport } from './routes/_authenticated/intel.index'
import { Route as AuthenticatedEngagementIndexRouteImport } from './routes/_authenticated/engagement/index'
import { Route as AuthenticatedPriorityUnitIdRouteImport } from './routes/_authenticated/priority/$unitId'
import { Route as AuthenticatedIntelUnitIdRouteImport } from './routes/_authenticated/intel.$unitId'
import { Route as AuthenticatedEngagementUnitIdRouteImport } from './routes/_authenticated/engagement/$unitId'
import { Route as AuthenticatedAllocateIntelIdRouteImport } from './routes/_authenticated/allocate.$intelId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes/_authenticated/admin/units'
import { Route as AuthenticatedAdminSatellitesRouteImport } from './routes/_authenticated/admin/satellites'
import { Route as AuthenticatedInventoryUnitIdIndexRouteImport } from './routes/_authenticated/inventory/$unitId/index'
import { Route as AuthenticatedIntelUnitIdSatelliteKeyRouteImport } from './routes/_authenticated/intel.$unitId.$satelliteKey'
import { Route as AuthenticatedInventoryUnitIdCategoryIdIndexRouteImport } from './routes/_authenticated/inventory/$unitId/$categoryId/index'
import { Route as AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRouteImport } from './routes/_authenticated/inventory/$unitId/$categoryId/$equipmentId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinutesRoute = AuthenticatedMinutesRouteImport.update({
  id: '/minutes',
  path: '/minutes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportantRoute = AuthenticatedImportantRouteImport.update({
  id: '/important',
  path: '/important',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscardedRoute = AuthenticatedDiscardedRouteImport.update({
  id: '/discarded',
  path: '/discarded',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlCenterRoute =
  AuthenticatedControlCenterRouteImport.update({
    id: '/control-center',
    path: '/control-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministratorRoute =
  AuthenticatedAdministratorRouteImport.update({
    id: '/administrator',
    path: '/administrator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisibilityIndexRoute =
  AuthenticatedVisibilityIndexRouteImport.update({
    id: '/visibility/',
    path: '/visibility/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceabilityIndexRoute =
  AuthenticatedServiceabilityIndexRouteImport.update({
    id: '/serviceability/',
    path: '/serviceability/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriorityIndexRoute =
  AuthenticatedPriorityIndexRouteImport.update({
    id: '/priority/',
    path: '/priority/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelIndexRoute = AuthenticatedIntelIndexRouteImport.update({
  id: '/intel/',
  path: '/intel/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngagementIndexRoute =
  AuthenticatedEngagementIndexRouteImport.update({
    id: '/engagement/',
    path: '/engagement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriorityUnitIdRoute =
  AuthenticatedPriorityUnitIdRouteImport.update({
    id: '/priority/$unitId',
    path: '/priority/$unitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelUnitIdRoute =
  AuthenticatedIntelUnitIdRouteImport.update({
    id: '/intel/$unitId',
    path: '/intel/$unitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementUnitIdRoute =
  AuthenticatedEngagementUnitIdRouteImport.update({
    id: '/engagement/$unitId',
    path: '/engagement/$unitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAllocateIntelIdRoute =
  AuthenticatedAllocateIntelIdRouteImport.update({
    id: '/allocate/$intelId',
    path: '/allocate/$intelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/admin/units',
  path: '/admin/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSatellitesRoute =
  AuthenticatedAdminSatellitesRouteImport.update({
    id: '/admin/satellites',
    path: '/admin/satellites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryUnitIdIndexRoute =
  AuthenticatedInventoryUnitIdIndexRouteImport.update({
    id: '/inventory/$unitId/',
    path: '/inventory/$unitId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelUnitIdSatelliteKeyRoute =
  AuthenticatedIntelUnitIdSatelliteKeyRouteImport.update({
    id: '/$satelliteKey',
    path: '/$satelliteKey',
    getParentRoute: () => AuthenticatedIntelUnitIdRoute,
  } as any)
const AuthenticatedInventoryUnitIdCategoryIdIndexRoute =
  AuthenticatedInventoryUnitIdCategoryIdIndexRouteImport.update({
    id: '/inventory/$unitId/$categoryId/',
    path: '/inventory/$unitId/$categoryId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute =
  AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRouteImport.update({
    id: '/inventory/$unitId/$categoryId/$equipmentId',
    path: '/inventory/$unitId/$categoryId/$equipmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/administrator': typeof AuthenticatedAdministratorRoute
  '/control-center': typeof AuthenticatedControlCenterRoute
  '/discarded': typeof AuthenticatedDiscardedRoute
  '/important': typeof AuthenticatedImportantRoute
  '/minutes': typeof AuthenticatedMinutesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/admin/satellites': typeof AuthenticatedAdminSatellitesRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/allocate/$intelId': typeof AuthenticatedAllocateIntelIdRoute
  '/engagement/$unitId': typeof AuthenticatedEngagementUnitIdRoute
  '/intel/$unitId': typeof AuthenticatedIntelUnitIdRouteWithChildren
  '/priority/$unitId': typeof AuthenticatedPriorityUnitIdRoute
  '/engagement/': typeof AuthenticatedEngagementIndexRoute
  '/intel/': typeof AuthenticatedIntelIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/priority/': typeof AuthenticatedPriorityIndexRoute
  '/serviceability/': typeof AuthenticatedServiceabilityIndexRoute
  '/visibility/': typeof AuthenticatedVisibilityIndexRoute
  '/intel/$unitId/$satelliteKey': typeof AuthenticatedIntelUnitIdSatelliteKeyRoute
  '/inventory/$unitId/': typeof AuthenticatedInventoryUnitIdIndexRoute
  '/inventory/$unitId/$categoryId/$equipmentId': typeof AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute
  '/inventory/$unitId/$categoryId/': typeof AuthenticatedInventoryUnitIdCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/administrator': typeof AuthenticatedAdministratorRoute
  '/control-center': typeof AuthenticatedControlCenterRoute
  '/discarded': typeof AuthenticatedDiscardedRoute
  '/important': typeof AuthenticatedImportantRoute
  '/minutes': typeof AuthenticatedMinutesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/satellites': typeof AuthenticatedAdminSatellitesRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/allocate/$intelId': typeof AuthenticatedAllocateIntelIdRoute
  '/engagement/$unitId': typeof AuthenticatedEngagementUnitIdRoute
  '/intel/$unitId': typeof AuthenticatedIntelUnitIdRouteWithChildren
  '/priority/$unitId': typeof AuthenticatedPriorityUnitIdRoute
  '/engagement': typeof AuthenticatedEngagementIndexRoute
  '/intel': typeof AuthenticatedIntelIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/priority': typeof AuthenticatedPriorityIndexRoute
  '/serviceability': typeof AuthenticatedServiceabilityIndexRoute
  '/visibility': typeof AuthenticatedVisibilityIndexRoute
  '/intel/$unitId/$satelliteKey': typeof AuthenticatedIntelUnitIdSatelliteKeyRoute
  '/inventory/$unitId': typeof AuthenticatedInventoryUnitIdIndexRoute
  '/inventory/$unitId/$categoryId/$equipmentId': typeof AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute
  '/inventory/$unitId/$categoryId': typeof AuthenticatedInventoryUnitIdCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administrator': typeof AuthenticatedAdministratorRoute
  '/_authenticated/control-center': typeof AuthenticatedControlCenterRoute
  '/_authenticated/discarded': typeof AuthenticatedDiscardedRoute
  '/_authenticated/important': typeof AuthenticatedImportantRoute
  '/_authenticated/minutes': typeof AuthenticatedMinutesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/satellites': typeof AuthenticatedAdminSatellitesRoute
  '/_authenticated/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/allocate/$intelId': typeof AuthenticatedAllocateIntelIdRoute
  '/_authenticated/engagement/$unitId': typeof AuthenticatedEngagementUnitIdRoute
  '/_authenticated/intel/$unitId': typeof AuthenticatedIntelUnitIdRouteWithChildren
  '/_authenticated/priority/$unitId': typeof AuthenticatedPriorityUnitIdRoute
  '/_authenticated/engagement/': typeof AuthenticatedEngagementIndexRoute
  '/_authenticated/intel/': typeof AuthenticatedIntelIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/priority/': typeof AuthenticatedPriorityIndexRoute
  '/_authenticated/serviceability/': typeof AuthenticatedServiceabilityIndexRoute
  '/_authenticated/visibility/': typeof AuthenticatedVisibilityIndexRoute
  '/_authenticated/intel/$unitId/$satelliteKey': typeof AuthenticatedIntelUnitIdSatelliteKeyRoute
  '/_authenticated/inventory/$unitId/': typeof AuthenticatedInventoryUnitIdIndexRoute
  '/_authenticated/inventory/$unitId/$categoryId/$equipmentId': typeof AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute
  '/_authenticated/inventory/$unitId/$categoryId/': typeof AuthenticatedInventoryUnitIdCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administrator'
    | '/control-center'
    | '/discarded'
    | '/important'
    | '/minutes'
    | '/reports'
    | '/admin/satellites'
    | '/admin/units'
    | '/admin/users'
    | '/allocate/$intelId'
    | '/engagement/$unitId'
    | '/intel/$unitId'
    | '/priority/$unitId'
    | '/engagement/'
    | '/intel/'
    | '/inventory/'
    | '/priority/'
    | '/serviceability/'
    | '/visibility/'
    | '/intel/$unitId/$satelliteKey'
    | '/inventory/$unitId/'
    | '/inventory/$unitId/$categoryId/$equipmentId'
    | '/inventory/$unitId/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/administrator'
    | '/control-center'
    | '/discarded'
    | '/important'
    | '/minutes'
    | '/reports'
    | '/'
    | '/admin/satellites'
    | '/admin/units'
    | '/admin/users'
    | '/allocate/$intelId'
    | '/engagement/$unitId'
    | '/intel/$unitId'
    | '/priority/$unitId'
    | '/engagement'
    | '/intel'
    | '/inventory'
    | '/priority'
    | '/serviceability'
    | '/visibility'
    | '/intel/$unitId/$satelliteKey'
    | '/inventory/$unitId'
    | '/inventory/$unitId/$categoryId/$equipmentId'
    | '/inventory/$unitId/$categoryId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administrator'
    | '/_authenticated/control-center'
    | '/_authenticated/discarded'
    | '/_authenticated/important'
    | '/_authenticated/minutes'
    | '/_authenticated/reports'
    | '/_authenticated/'
    | '/_authenticated/admin/satellites'
    | '/_authenticated/admin/units'
    | '/_authenticated/admin/users'
    | '/_authenticated/allocate/$intelId'
    | '/_authenticated/engagement/$unitId'
    | '/_authenticated/intel/$unitId'
    | '/_authenticated/priority/$unitId'
    | '/_authenticated/engagement/'
    | '/_authenticated/intel/'
    | '/_authenticated/inventory/'
    | '/_authenticated/priority/'
    | '/_authenticated/serviceability/'
    | '/_authenticated/visibility/'
    | '/_authenticated/intel/$unitId/$satelliteKey'
    | '/_authenticated/inventory/$unitId/'
    | '/_authenticated/inventory/$unitId/$categoryId/$equipmentId'
    | '/_authenticated/inventory/$unitId/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minutes': {
      id: '/_authenticated/minutes'
      path: '/minutes'
      fullPath: '/minutes'
      preLoaderRoute: typeof AuthenticatedMinutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/important': {
      id: '/_authenticated/important'
      path: '/important'
      fullPath: '/important'
      preLoaderRoute: typeof AuthenticatedImportantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discarded': {
      id: '/_authenticated/discarded'
      path: '/discarded'
      fullPath: '/discarded'
      preLoaderRoute: typeof AuthenticatedDiscardedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-center': {
      id: '/_authenticated/control-center'
      path: '/control-center'
      fullPath: '/control-center'
      preLoaderRoute: typeof AuthenticatedControlCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrator': {
      id: '/_authenticated/administrator'
      path: '/administrator'
      fullPath: '/administrator'
      preLoaderRoute: typeof AuthenticatedAdministratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visibility/': {
      id: '/_authenticated/visibility/'
      path: '/visibility'
      fullPath: '/visibility/'
      preLoaderRoute: typeof AuthenticatedVisibilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/serviceability/': {
      id: '/_authenticated/serviceability/'
      path: '/serviceability'
      fullPath: '/serviceability/'
      preLoaderRoute: typeof AuthenticatedServiceabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priority/': {
      id: '/_authenticated/priority/'
      path: '/priority'
      fullPath: '/priority/'
      preLoaderRoute: typeof AuthenticatedPriorityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intel/': {
      id: '/_authenticated/intel/'
      path: '/intel'
      fullPath: '/intel/'
      preLoaderRoute: typeof AuthenticatedIntelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagement/': {
      id: '/_authenticated/engagement/'
      path: '/engagement'
      fullPath: '/engagement/'
      preLoaderRoute: typeof AuthenticatedEngagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priority/$unitId': {
      id: '/_authenticated/priority/$unitId'
      path: '/priority/$unitId'
      fullPath: '/priority/$unitId'
      preLoaderRoute: typeof AuthenticatedPriorityUnitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intel/$unitId': {
      id: '/_authenticated/intel/$unitId'
      path: '/intel/$unitId'
      fullPath: '/intel/$unitId'
      preLoaderRoute: typeof AuthenticatedIntelUnitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagement/$unitId': {
      id: '/_authenticated/engagement/$unitId'
      path: '/engagement/$unitId'
      fullPath: '/engagement/$unitId'
      preLoaderRoute: typeof AuthenticatedEngagementUnitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allocate/$intelId': {
      id: '/_authenticated/allocate/$intelId'
      path: '/allocate/$intelId'
      fullPath: '/allocate/$intelId'
      preLoaderRoute: typeof AuthenticatedAllocateIntelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/units': {
      id: '/_authenticated/admin/units'
      path: '/admin/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/satellites': {
      id: '/_authenticated/admin/satellites'
      path: '/admin/satellites'
      fullPath: '/admin/satellites'
      preLoaderRoute: typeof AuthenticatedAdminSatellitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/$unitId/': {
      id: '/_authenticated/inventory/$unitId/'
      path: '/inventory/$unitId'
      fullPath: '/inventory/$unitId/'
      preLoaderRoute: typeof AuthenticatedInventoryUnitIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intel/$unitId/$satelliteKey': {
      id: '/_authenticated/intel/$unitId/$satelliteKey'
      path: '/$satelliteKey'
      fullPath: '/intel/$unitId/$satelliteKey'
      preLoaderRoute: typeof AuthenticatedIntelUnitIdSatelliteKeyRouteImport
      parentRoute: typeof AuthenticatedIntelUnitIdRoute
    }
    '/_authenticated/inventory/$unitId/$categoryId/': {
      id: '/_authenticated/inventory/$unitId/$categoryId/'
      path: '/inventory/$unitId/$categoryId'
      fullPath: '/inventory/$unitId/$categoryId/'
      preLoaderRoute: typeof AuthenticatedInventoryUnitIdCategoryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/$unitId/$categoryId/$equipmentId': {
      id: '/_authenticated/inventory/$unitId/$categoryId/$equipmentId'
      path: '/inventory/$unitId/$categoryId/$equipmentId'
      fullPath: '/inventory/$unitId/$categoryId/$equipmentId'
      preLoaderRoute: typeof AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedIntelUnitIdRouteChildren {
  AuthenticatedIntelUnitIdSatelliteKeyRoute: typeof AuthenticatedIntelUnitIdSatelliteKeyRoute
}

const AuthenticatedIntelUnitIdRouteChildren: AuthenticatedIntelUnitIdRouteChildren =
  {
    AuthenticatedIntelUnitIdSatelliteKeyRoute:
      AuthenticatedIntelUnitIdSatelliteKeyRoute,
  }

const AuthenticatedIntelUnitIdRouteWithChildren =
  AuthenticatedIntelUnitIdRoute._addFileChildren(
    AuthenticatedIntelUnitIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministratorRoute: typeof AuthenticatedAdministratorRoute
  AuthenticatedControlCenterRoute: typeof AuthenticatedControlCenterRoute
  AuthenticatedDiscardedRoute: typeof AuthenticatedDiscardedRoute
  AuthenticatedImportantRoute: typeof AuthenticatedImportantRoute
  AuthenticatedMinutesRoute: typeof AuthenticatedMinutesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminSatellitesRoute: typeof AuthenticatedAdminSatellitesRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAllocateIntelIdRoute: typeof AuthenticatedAllocateIntelIdRoute
  AuthenticatedEngagementUnitIdRoute: typeof AuthenticatedEngagementUnitIdRoute
  AuthenticatedIntelUnitIdRoute: typeof AuthenticatedIntelUnitIdRouteWithChildren
  AuthenticatedPriorityUnitIdRoute: typeof AuthenticatedPriorityUnitIdRoute
  AuthenticatedEngagementIndexRoute: typeof AuthenticatedEngagementIndexRoute
  AuthenticatedIntelIndexRoute: typeof AuthenticatedIntelIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedPriorityIndexRoute: typeof AuthenticatedPriorityIndexRoute
  AuthenticatedServiceabilityIndexRoute: typeof AuthenticatedServiceabilityIndexRoute
  AuthenticatedVisibilityIndexRoute: typeof AuthenticatedVisibilityIndexRoute
  AuthenticatedInventoryUnitIdIndexRoute: typeof AuthenticatedInventoryUnitIdIndexRoute
  AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute: typeof AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute
  AuthenticatedInventoryUnitIdCategoryIdIndexRoute: typeof AuthenticatedInventoryUnitIdCategoryIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministratorRoute: AuthenticatedAdministratorRoute,
  AuthenticatedControlCenterRoute: AuthenticatedControlCenterRoute,
  AuthenticatedDiscardedRoute: AuthenticatedDiscardedRoute,
  AuthenticatedImportantRoute: AuthenticatedImportantRoute,
  AuthenticatedMinutesRoute: AuthenticatedMinutesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminSatellitesRoute: AuthenticatedAdminSatellitesRoute,
  AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAllocateIntelIdRoute: AuthenticatedAllocateIntelIdRoute,
  AuthenticatedEngagementUnitIdRoute: AuthenticatedEngagementUnitIdRoute,
  AuthenticatedIntelUnitIdRoute: AuthenticatedIntelUnitIdRouteWithChildren,
  AuthenticatedPriorityUnitIdRoute: AuthenticatedPriorityUnitIdRoute,
  AuthenticatedEngagementIndexRoute: AuthenticatedEngagementIndexRoute,
  AuthenticatedIntelIndexRoute: AuthenticatedIntelIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedPriorityIndexRoute: AuthenticatedPriorityIndexRoute,
  AuthenticatedServiceabilityIndexRoute: AuthenticatedServiceabilityIndexRoute,
  AuthenticatedVisibilityIndexRoute: AuthenticatedVisibilityIndexRoute,
  AuthenticatedInventoryUnitIdIndexRoute:
    AuthenticatedInventoryUnitIdIndexRoute,
  AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute:
    AuthenticatedInventoryUnitIdCategoryIdEquipmentIdRoute,
  AuthenticatedInventoryUnitIdCategoryIdIndexRoute:
    AuthenticatedInventoryUnitIdCategoryIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
